# Generated by Django 3.1.2 on 2020-10-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_party_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='Susan', max_length=32),
            preserve_default=False,
        ),
    ]
